name: Update README

on:
  push:
    branches:
      - matser  # 블로그 레파지토리의 기본 브랜치

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find new Markdown files
        id: find-files
        run: |
          touch new_files.txt
          git diff --name-only HEAD^ HEAD >> new_files.txt

      - name: Update TIL README
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');

            const filePath = 'new_files.txt';
            const markdownFiles = fs.readFileSync(filePath, 'utf8').split('\n');
            const today = new Date().toISOString().slice(0, 10);

            const tilReadmePath = '../../README.md';
            let tilReadmeContent = fs.readFileSync(tilReadmePath, 'utf8');

            markdownFiles.forEach(file => {
              if (file.endsWith('.md')) {
                const fileLink = `- [${today}](${file})`;
                tilReadmeContent += `\n${fileLink}`;
              }
            });

            fs.writeFileSync(tilReadmePath, tilReadmeContent);
